#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook..."
cd "$(git rev-parse --show-toplevel)" # Navigate to project root
echo "Current directory: $(pwd)"
npm run lint && npm run build
